FROM samoilenko/php_base:latest

RUN  pecl install xdebug-2.6.1 \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install bcmath

COPY docker/conf/xdebug.ini /usr/local/etc/php/conf.d

RUN { \
		echo 'opcache.revalidate_freq=0'; \
	} > /usr/local/etc/php/conf.d/opcache-recommended.ini

RUN mkdir -p /project/cache && chown -R www-data:www-data /project/cache
